#!/bin/bash

# Set the base directory to the root directory.
BASE_DIR="./"

# Change directory to the 'files' folder located in the root directory.
cd "${BASE_DIR}files" || exit

# Iterate through each file in the 'files' directory.
for file in *; do
  if [ -f "$file" ]; then # Check if it is a regular file (not a directory).
    # Extract the first letter of the filename, convert it to lowercase.
    first_letter=$(echo "$file" | cut -c1 | tr '[:upper:]' '[:lower:]')

    # Construct the path to the target directory.
    target_dir="../${first_letter}"

    # Move the file to the target directory.
    mv "$file" "$target_dir/"
  fi
done

echo "Files have been moved to their respective directories."
